/**
 * Scheduling engine — one `planNext()` returning a SchedulingPlan.
 *
 * @see Section 5.10 of pi-package-refactor-plan.md for the interface contract.
 * Stub factory — real implementation in R-S9.
 */

import type { PipelineRunState, DispatchCandidate, GateResultRecord } from "../shared/types.js";
import type { OrchestratorConfig } from "../config.js";
import type { WorkerHandle } from "../workers/pool/index.js";

// ═══════════════════════════════════════════════════════════════════════════
// Public Types
// ═══════════════════════════════════════════════════════════════════════════

/** Evidence context provided to the scheduler. */
export interface SchedulingEvidence {
  /** Current pipeline state. */
  state: PipelineRunState;
  /** Active worker handles. */
  activeWorkers: WorkerHandle[];
  /** Check if an artifact exists on disk. */
  artifactExists: (path: string) => Promise<boolean>;
}

/** Approval request generated by the scheduler. */
export interface ApprovalRequest {
  /** Subject of the approval. */
  subject: string;
  /** Context for the human reviewer. */
  context: string;
}

/** Result of a scheduling plan evaluation. */
export interface SchedulingPlan {
  /** Work ready to dispatch. */
  dispatches: DispatchCandidate[];
  /** Work blocked and why. */
  blocked: { id: string; reason: string }[];
  /** Phase gate evaluation results. */
  gateResults: GateResultRecord[];
  /** Required human approvals before dispatch. */
  requiredApprovals: ApprovalRequest[];
  /** Recommended next action for operator display. */
  nextAction: string | null;
}

/** Scheduler that answers "what should be dispatched next?". */
export interface Scheduler {
  /** Evaluate all constraints and return a scheduling plan. */
  planNext(evidence: SchedulingEvidence): Promise<SchedulingPlan>;
}

/**
 * Creates a Scheduler instance.
 * Stub — returns an empty plan. Real implementation in R-S9.
 *
 * @param _config - Orchestrator configuration (unused in stub).
 *
 * @returns Scheduler instance.
 *
 * @example
 * ```typescript
 * const scheduler = createScheduler(config);
 * const plan = await scheduler.planNext(evidence);
 * ```
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars -- stub
export function createScheduler(_config: OrchestratorConfig): Scheduler {
  return {
    planNext: () =>
      Promise.resolve({
        dispatches: [],
        blocked: [],
        gateResults: [],
        requiredApprovals: [],
        nextAction: null,
      }),
  };
}
